// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef modifiers_editor_h
#define modifiers_editor_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>

class Modifiers_Editor : public Fl_Group {
public:
  Modifiers_Editor(int X, int Y, int W, int H, const char *L = 0);
  Fl_Group *mod_A1;
  Fl_Group *mod_A2;
  Fl_Group *mod_A3;
  Fl_Group *mod_A4;
  Fl_Group *mod_A5;
  Fl_Group *mod_A6;
  Fl_Group *mod_A7;
  Fl_Group *mod_A8;
  Fl_Group *mod_A9;
  Fl_Group *mod_A10;
  Fl_Box *lbl_A;
  Fl_Group *mod_B1;
  Fl_Group *mod_B2;
  Fl_Group *mod_B3;
  Fl_Group *mod_B4;
  Fl_Group *mod_B5;
  Fl_Group *mod_B6;
  Fl_Group *mod_B7;
  Fl_Group *mod_B8;
  Fl_Group *mod_B9;
  Fl_Group *mod_B10;
  Fl_Box *lbl_B;
  Fl_Group *mod_C1;
  Fl_Group *mod_C2;
  Fl_Group *mod_C3;
  Fl_Group *mod_C4;
  Fl_Group *mod_C5;
  Fl_Group *mod_C6;
  Fl_Group *mod_C7;
  Fl_Group *mod_C8;
  Fl_Group *mod_C9;
  Fl_Group *mod_C10;
  Fl_Box *lbl_C;
  Fl_Group *mod_D1;
  Fl_Group *mod_D2;
  Fl_Group *mod_D3;
  Fl_Group *mod_D4;
  Fl_Group *mod_D5;
  Fl_Group *mod_D6;
  Fl_Group *mod_D7;
  Fl_Group *mod_D8;
  Fl_Group *mod_D9;
  Fl_Group *mod_D10;
  Fl_Box *lbl_D;
  Fl_Group *mod_E1;
  Fl_Group *mod_E2;
  Fl_Group *mod_E3;
  Fl_Group *mod_E4;
  Fl_Group *mod_E5;
  Fl_Group *mod_E6;
  Fl_Group *mod_E7;
  Fl_Group *mod_E8;
  Fl_Group *mod_E9;
  Fl_Group *mod_E10;
  Fl_Box *lbl_E;
};
#endif
