// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "app_i18n.h"
#include "receive_dialog.h"
#include "model/patch.h"

void Receive_Dialog::cb_Cancel_i(Fl_Button*, void*) {
  window_->hide();
}
void Receive_Dialog::cb_Cancel(Fl_Button* o, void* v) {
  ((Receive_Dialog*)(o->parent()->user_data()))->cb_Cancel_i(o,v);
}

void Receive_Dialog::cb_OK_i(Fl_Button*, void*) {
  accept_ = true;
window_->hide();
}
void Receive_Dialog::cb_OK(Fl_Button* o, void* v) {
  ((Receive_Dialog*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

int Receive_Dialog::show(const char *title) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(420, 110);
    w = o; if (w) {/* empty */}
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(345, 75, 65, 25, _("Cancel"));
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_Cancel);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(265, 75, 65, 25, _("OK"));
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Button* o
    { val_rx_programs = new Fl_Value_Output(370, 15, 40, 20, _("Programs received"));
      val_rx_programs->labelsize(12);
      val_rx_programs->textsize(12);
    } // Fl_Value_Output* val_rx_programs
    { val_rx_messages = new Fl_Value_Output(370, 40, 40, 20, _("Message count"));
      val_rx_messages->labelsize(12);
      val_rx_messages->textsize(12);
    } // Fl_Value_Output* val_rx_messages
    { Fl_Box* o = new Fl_Box(10, 10, 215, 90, _("Send a Bulk Dump from the machine and validate when finished. Warning: This p\
rocess overwrites the current bank."));
      o->box(FL_THIN_UP_BOX);
      o->labelsize(12);
      o->align(Fl_Align(133|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    o->end();
  } // Fl_Double_Window* o
  accept_ = false;
  window_ = w;
  
  w->label(title);
  
  begin_receive();
  
  w->set_modal();
  w->show();
  while (w->shown()) Fl::wait();
  
  end_receive();
  
  delete w;
  window_ = nullptr;
  if (!accept_)
      return -1;
  
  return 0;
}
