// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "app_i18n.h"
#include "singlemod_editor.h"
Single_Mod_Editor::Single_Mod_Editor(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
{ sl_assignment = new Fl_Slider(5, 20, 20, 70);
  sl_assignment->type(2);
  sl_assignment->labelsize(12);
} // Fl_Slider* sl_assignment
{ sl_min = new Fl_Slider(25, 20, 20, 70);
  sl_min->type(2);
  sl_min->labelsize(12);
} // Fl_Slider* sl_min
{ sl_mid = new Fl_Slider(45, 20, 20, 70);
  sl_mid->type(2);
  sl_mid->labelsize(12);
} // Fl_Slider* sl_mid
{ sl_max = new Fl_Slider(65, 20, 20, 70);
  sl_max->type(2);
  sl_max->labelsize(12);
} // Fl_Slider* sl_max
{ lbl_assignment = new Fl_Box(5, 0, 20, 20, _("off"));
  lbl_assignment->labelsize(10);
} // Fl_Box* lbl_assignment
{ lbl_min = new Fl_Box(25, 0, 20, 20, _("100"));
  lbl_min->labelsize(10);
} // Fl_Box* lbl_min
{ lbl_mid = new Fl_Box(45, 0, 20, 20, _("100"));
  lbl_mid->labelsize(10);
} // Fl_Box* lbl_mid
{ lbl_max = new Fl_Box(65, 0, 20, 20, _("100"));
  lbl_max->labelsize(10);
} // Fl_Box* lbl_max
end();
}
