// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef singlemod_editor_h
#define singlemod_editor_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>

class Single_Mod_Editor : public Fl_Group {
public:
  Single_Mod_Editor(int X, int Y, int W, int H, const char *L = 0);
  Fl_Slider *sl_assignment;
  Fl_Slider *sl_min;
  Fl_Slider *sl_mid;
  Fl_Slider *sl_max;
  Fl_Box *lbl_assignment;
  Fl_Box *lbl_min;
  Fl_Box *lbl_mid;
  Fl_Box *lbl_max;
};
#endif
